### ISSUE TITLE
Query log should be off by default

### ISSUE THREAD

**Issue by arobert3434** [glats/alpine-lamp#6]
The Dockerfile runs commands to explicitly turn the [MySQL general log](https://dev.mysql.com/doc/refman/8.0/en/query-log.html) on, meaning every query gets logged to a file. This can impact performance and also cause a growing file inside the container. It would be better to leave this off by default (like MySQL out of the box does) and let users turn it on themselves if they need to.

**Comment by glats** [comment]
I don't think so.
This docker is only for development. You can destroy or clean it whatever you want.

**Comment by glats** [comment]
since there's no answer i'll close this issue.
