### ISSUE TITLE
Possible copy/paste mistake in README.md

### ISSUE THREAD

**Issue by tneigerux** [glats/alpine-lamp#7]
In the README. you have two very similar commands twice, and I'd expect the first one to be a variation of ```docker pull```, not ```docker run```.

Here:
https://github.com/j1cs/docker-lamp#grab-from-docker-hub

and here:
https://github.com/j1cs/docker-lamp#run-it

I'm just learning so I could be wrong. Is this intentional?

**Comment by glats** [comment]
Yes. If the image doesn't exist docker download it automatically with pull.

**Comment by glats** [comment]
Also the third command is to run your own image. you know? look at the end of the command it appears the var $USER. It came after the build command.
